spring.application.name=Ambifericos
spring.datasource.url=jdbc:postgresql://ambifericos-germinare-4a22.g.aivencloud.com:17994/defaultdb
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect