spring.application.name=Ambifericos
spring.datasource.url=jdbc:postgresql://ambifericos-germinare-4a22.g.aivencloud.com:17994/defaultdb
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_8LCYvFQ70Wq3pOVxMMV

